#!/usr/bin/env python3
"""jxtest install / uninstall — set up the CLI and Claude Code skill links.

When `jxtest` is installed via pip or cloned from source, the user often wants
to expose its sub-skills to Claude Code so a single slash-command (or auto-
trigger) can run e.g. `jxtest run` without typing the full path.

Claude Code reads skills from `~/.claude/skills/<name>/SKILL.md`. We just need
a link per skill directory + a `SKILL.md` (already present in each skill
directory inside this repo).

Usage:
  jxtest install                # link all 17 skills + the CLI itself
  jxtest install --dry-run      # show what would happen, don't modify
  jxtest uninstall              # remove what install created

Platform handling
-----------------
POSIX (macOS / Linux):
  - skills → symlinks in `~/.claude/skills/`
  - CLI    → symlink `~/.local/bin/jxtest` → `bin/jxtest`

Windows:
  - skills → *directory junctions*. Plain symlinks need admin rights or
    Developer Mode; junctions need neither and read identically, so the
    default path never asks the user to elevate.
  - CLI    → a generated `jxtest.cmd` shim in Python's Scripts directory
    (which is on PATH whenever Python was installed with "Add to PATH").
    `bin/jxtest` is a shebang script, so it can't just be copied to `.cmd` —
    cmd.exe would try to interpret Python source as batch.

The installer is self-bootstrap: it works whether invoked via `bin/jxtest`
or directly (e.g. `python3 install.py install`).
"""
import argparse
import os
import shutil
import subprocess
import sys
import sysconfig
from pathlib import Path

# Self-bootstrap for direct invocation
_THIS = Path(__file__).resolve()
sys.path.insert(0, str(_THIS.parent.parent.parent))


# SKILLS_ROOT = .../jxtest/skills. install.py lives at
# skills/api-test-installer/scripts/install.py, so go up 3 levels to reach skills/.
SKILLS_ROOT = _THIS.parent.parent.parent  # .../jxtest/skills

IS_WINDOWS = os.name == "nt"

# Skill directories that should be exposed to Claude Code. Anything else in
# skills/ (e.g. _common, api-test-installer itself) is internal infrastructure
# and shouldn't show up as a slash-command.
INSTALLABLE_SKILLS = [
    "api-test-schema", "api-test-gen", "api-test-env", "api-test-mock",
    "api-test-run", "api-test-load", "api-test-heal", "api-test-report",
    "api-test-doc", "api-test-security", "api-test-diff", "api-test-coverage",
    "api-test-completion", "api-test-scenario", "api-test-factory",
    "api-test-suite", "api-test-doctor",
]

CLAUDE_SKILLS_DIR = Path.home() / ".claude" / "skills"

# The CLI entrypoint itself. Linking the skills is only half the job — if
# `jxtest` isn't on PATH, every SKILL.md instruction that starts with `jxtest`
# is a dead end, and `jxtest install` can't even be run to repair it. The
# link also goes stale whenever the repo is moved (experience report
# 2026-08-04: ~/.local/bin/jxtest still pointed into a deleted .trae/skills path).
JXTEST_BIN = SKILLS_ROOT.parent / "bin" / "jxtest"

# Marks a generated Windows shim so uninstall can tell ours from a file the
# user (or pip) put there.
SHIM_MARKER = "jxtest-shim"


def cli_target() -> Path:
    """Where the `jxtest` command should live for this platform."""
    if IS_WINDOWS:
        # Python's Scripts dir is already on PATH for a standard install, so
        # the shim is usable without asking the user to edit PATH.
        return Path(sysconfig.get_path("scripts")) / "jxtest.cmd"
    return Path.home() / ".local" / "bin" / "jxtest"


def _shim_body() -> str:
    """A .cmd shim that forwards every argument to bin/jxtest.

    Pins the interpreter to the one running the installer: on machines with
    several Pythons, a bare `python` can resolve to one without pyyaml.

    CRLF is explicit because cmd.exe is unreliable with LF-only batch files.
    Callers must read/write this as *bytes* — text mode on Windows would
    translate the `\\n` again and emit `\\r\\r\\n`.
    """
    return (
        "@echo off\r\n"
        f":: {SHIM_MARKER} — generated by `jxtest install`; safe to delete\r\n"
        f'"{sys.executable}" "{JXTEST_BIN}" %*\r\n'
    )


def _read_shim(p: Path) -> str:
    """Read a shim verbatim. Byte-level so newlines survive the round-trip and
    the idempotency comparison in `_install_cli_windows` can actually match."""
    return p.read_bytes().decode("utf-8", errors="replace")


def _link_target(p: Path) -> Path | None:
    """Target of a symlink or Windows junction, or None if `p` isn't a link.

    `os.readlink` covers both on Python 3.8+, which matters because
    `Path.is_symlink()` reports False for junctions — the mechanism we use on
    Windows — and would make our own links look like foreign directories.
    """
    try:
        return Path(os.readlink(p))
    except OSError:
        return None


def _is_link(p: Path) -> bool:
    return p.is_symlink() or _link_target(p) is not None


def _unlink_any(p: Path) -> None:
    """Detach a symlink or junction without touching what it points at."""
    try:
        p.unlink()
    except OSError:
        # Windows directory symlinks and junctions are removed with rmdir.
        # This deletes the link entry only; the target directory survives.
        os.rmdir(p)


def _points_at(link: Path, src: Path) -> bool:
    """True if `link` already resolves to `src`."""
    target = _link_target(link)
    if target is None:
        return False
    try:
        return (target if target.is_absolute() else link.parent / target).resolve() == src.resolve()
    except OSError:
        return False


def _make_dir_link(src: Path, dst: Path) -> str:
    """Link directory `dst` → `src`. Returns the mechanism used.

    Raises OSError if neither mechanism is available, so callers can report a
    real reason instead of a traceback.
    """
    if not IS_WINDOWS:
        dst.symlink_to(src)
        return "symlink"
    try:
        dst.symlink_to(src, target_is_directory=True)
        return "symlink"
    except OSError:
        # Unprivileged Windows refuses symlinks unless Developer Mode is on.
        # Junctions have no such restriction and resolve the same way for
        # every read Claude Code performs.
        proc = subprocess.run(["cmd", "/c", "mklink", "/J", str(dst), str(src)],
                              capture_output=True, text=True)
        if proc.returncode != 0:
            raise OSError(proc.stderr.strip() or "mklink /J failed")
        return "junction"


# --------------------------------------------------------------------------
# CLI entrypoint
# --------------------------------------------------------------------------

def _install_cli_windows(args: argparse.Namespace) -> None:
    """Write (or refresh) the jxtest.cmd shim in Python's Scripts directory."""
    dst = cli_target()
    body = _shim_body()

    if dst.exists():
        existing = _read_shim(dst)
        if SHIM_MARKER not in existing and not args.force:
            print(f"  ⚠ {dst} exists and wasn't generated by jxtest "
                  f"(maybe a pip install). Pass --force to replace.", file=sys.stderr)
            return
        if existing == body:
            print(f"  · CLI shim already current: {dst}", file=sys.stderr)
            return
        verb = "would refresh" if args.dry_run else "refreshed"
    else:
        verb = "would create" if args.dry_run else "created"

    if args.dry_run:
        print(f"[dry-run] {verb} CLI shim {dst} → {JXTEST_BIN}", file=sys.stderr)
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes(body.encode("utf-8"))
    print(f"  ✓ {verb} CLI shim: {dst} → {JXTEST_BIN}", file=sys.stderr)


def _install_cli_posix(args: argparse.Namespace) -> None:
    """Symlink bin/jxtest into ~/.local/bin, repairing a stale link if present."""
    dst = cli_target()

    if not dst.parent.exists():
        if args.dry_run:
            print(f"[dry-run] would create {dst.parent}", file=sys.stderr)
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            print(f"  ✓ created {dst.parent}", file=sys.stderr)

    if _is_link(dst):
        if _points_at(dst, JXTEST_BIN):
            print(f"  · CLI already linked: {dst}", file=sys.stderr)
        elif args.dry_run:
            state = "stale" if not dst.exists() else "pointing elsewhere"
            print(f"[dry-run] would relink {dst} ({state}: {dst.resolve()}) → {JXTEST_BIN}",
                  file=sys.stderr)
        else:
            # Replacing a link destroys no data, so repair it without --force.
            was_broken = not dst.exists()
            _unlink_any(dst)
            dst.symlink_to(JXTEST_BIN)
            label = "repaired broken" if was_broken else "repointed"
            print(f"  ✓ {label} CLI link: {dst} → {JXTEST_BIN}", file=sys.stderr)
    elif dst.exists():
        # A real file — could be a pip-installed entrypoint. Never clobber
        # without an explicit --force.
        if not args.force:
            print(f"  ⚠ {dst} exists and is a real file (maybe a pip install). "
                  f"Pass --force to replace.", file=sys.stderr)
        elif args.dry_run:
            print(f"[dry-run] would replace real file {dst} → {JXTEST_BIN}", file=sys.stderr)
        else:
            dst.unlink()
            dst.symlink_to(JXTEST_BIN)
            print(f"  ⟳ replaced {dst} → {JXTEST_BIN}", file=sys.stderr)
    elif args.dry_run:
        print(f"[dry-run] would symlink {dst} → {JXTEST_BIN}", file=sys.stderr)
    else:
        dst.symlink_to(JXTEST_BIN)
        print(f"  ✓ linked CLI: {dst} → {JXTEST_BIN}", file=sys.stderr)


def _install_cli(args: argparse.Namespace) -> None:
    if not JXTEST_BIN.exists():
        print(f"  ✗ CLI not found at {JXTEST_BIN}", file=sys.stderr)
        return
    try:
        if IS_WINDOWS:
            _install_cli_windows(args)
        else:
            _install_cli_posix(args)
    except OSError as e:
        print(f"  ✗ could not install the CLI: {e}", file=sys.stderr)
        print(f"    Run jxtest as: {sys.executable} {JXTEST_BIN} <command>", file=sys.stderr)
        return
    _warn_if_not_on_path()


def _warn_if_not_on_path() -> None:
    target_dir = cli_target().parent
    entries = {Path(p).expanduser() for p in os.environ.get("PATH", "").split(os.pathsep) if p}
    if target_dir in entries:
        return
    print(f"\n  ⚠ {target_dir} is not on your PATH — `jxtest` won't resolve.", file=sys.stderr)
    if IS_WINDOWS:
        print(f"    PowerShell (this session):  $env:Path = \"{target_dir};$env:Path\"\n"
              f"    Permanent:                  setx PATH \"{target_dir};%PATH%\"", file=sys.stderr)
    else:
        print(f"    Add to ~/.zshrc:  export PATH=\"$HOME/.local/bin:$PATH\"", file=sys.stderr)


def _uninstall_cli(args: argparse.Namespace) -> None:
    """Remove whatever install created for the CLI, on either platform."""
    dst = cli_target()

    if IS_WINDOWS:
        if not dst.exists():
            return
        if SHIM_MARKER not in _read_shim(dst):
            print(f"  · left {dst} alone (not a jxtest-generated shim)", file=sys.stderr)
            return
        if args.dry_run:
            print(f"[dry-run] would delete {dst}", file=sys.stderr)
        else:
            dst.unlink()
            print(f"  ✓ removed CLI shim: {dst}", file=sys.stderr)
        return

    if not _is_link(dst):
        if dst.exists():
            print(f"  · left {dst} alone (real file, not our link)", file=sys.stderr)
        return
    if not _points_at(dst, JXTEST_BIN):
        print(f"  · left {dst} alone (points to {dst.resolve()}, not this repo)", file=sys.stderr)
        return
    if args.dry_run:
        print(f"[dry-run] would unlink {dst}", file=sys.stderr)
    else:
        _unlink_any(dst)
        print(f"  ✓ removed CLI link: {dst}", file=sys.stderr)


# --------------------------------------------------------------------------
# Skills
# --------------------------------------------------------------------------

def cmd_install(args: argparse.Namespace) -> None:
    """Link each installable skill into ~/.claude/skills/, then the CLI."""
    if not CLAUDE_SKILLS_DIR.exists():
        if args.dry_run:
            print(f"[dry-run] would create {CLAUDE_SKILLS_DIR}", file=sys.stderr)
        else:
            CLAUDE_SKILLS_DIR.mkdir(parents=True, exist_ok=True)
            print(f"  ✓ created {CLAUDE_SKILLS_DIR}", file=sys.stderr)

    created: list[str] = []
    skipped_existing: list[str] = []
    replaced: list[str] = []
    failed: list[str] = []
    mechanisms: set[str] = set()

    def link(src: Path, dst: Path, name: str, bucket: list[str]) -> None:
        try:
            mechanisms.add(_make_dir_link(src, dst))
            bucket.append(name)
        except OSError as e:
            failed.append(f"{name}: {e}")

    for name in INSTALLABLE_SKILLS:
        src = SKILLS_ROOT / name
        if not src.exists():
            print(f"  ✗ {name}: not found at {src}", file=sys.stderr)
            continue
        dst = CLAUDE_SKILLS_DIR / name
        if dst.exists() or _is_link(dst):
            if _points_at(dst, src):
                skipped_existing.append(name)
                continue
            # Something else is here. If it's a link we can swap it freely;
            # a real directory may hold the user's own work, so that needs
            # --force.
            if _is_link(dst):
                if args.dry_run:
                    print(f"[dry-run] would relink {dst} → {src}", file=sys.stderr)
                else:
                    _unlink_any(dst)
                    link(src, dst, name, replaced)
            elif args.force:
                if args.dry_run:
                    print(f"[dry-run] would replace {dst} → {src}", file=sys.stderr)
                else:
                    shutil.rmtree(dst)
                    link(src, dst, name, replaced)
            else:
                print(f"  ⚠ {name}: {dst} already exists (not a link). "
                      f"Pass --force to replace.", file=sys.stderr)
            continue
        if args.dry_run:
            print(f"[dry-run] would link {dst} → {src}", file=sys.stderr)
        else:
            link(src, dst, name, created)

    print("", file=sys.stderr)
    print(f"jxtest install: {len(created)} created, {len(replaced)} replaced, "
          f"{len(skipped_existing)} already correct", file=sys.stderr)
    if not args.dry_run:
        if created:
            print(f"  ✓ created: {', '.join(created)}", file=sys.stderr)
        if replaced:
            print(f"  ⟳ replaced: {', '.join(replaced)}", file=sys.stderr)
        if skipped_existing:
            print(f"  · already installed: {len(skipped_existing)} skills "
                  f"(use --force to re-link)", file=sys.stderr)
        if "junction" in mechanisms:
            print(f"  · used directory junctions (no admin rights needed); "
                  f"enable Developer Mode if you'd rather have symlinks", file=sys.stderr)
    if failed:
        print(f"\n  ✗ {len(failed)} skill(s) could not be linked:", file=sys.stderr)
        for f in failed:
            print(f"    {f}", file=sys.stderr)
        if IS_WINDOWS:
            print(f"    On Windows this usually means both symlinks and junctions were\n"
                  f"    refused — try an elevated prompt, or turn on Developer Mode.", file=sys.stderr)
    if created or replaced:
        print(f"\n  Next: open Claude Code — skills should appear automatically. "
              f"Verify with: {'dir' if IS_WINDOWS else 'ls -la'} {CLAUDE_SKILLS_DIR}", file=sys.stderr)

    print("", file=sys.stderr)
    _install_cli(args)


def cmd_uninstall(args: argparse.Namespace) -> None:
    """Remove jxtest's links from ~/.claude/skills/, then the CLI."""
    removed: list[str] = []
    not_jxtest: list[str] = []
    would_remove = 0

    for name in INSTALLABLE_SKILLS:
        dst = CLAUDE_SKILLS_DIR / name
        if not dst.exists() and not _is_link(dst):
            continue
        if not _is_link(dst):
            not_jxtest.append(f"{name} (not a link)")
            continue
        if not _points_at(dst, SKILLS_ROOT / name):
            not_jxtest.append(f"{name} → {dst.resolve()}")
            continue
        if args.dry_run:
            print(f"[dry-run] would unlink {dst}", file=sys.stderr)
            would_remove += 1
        else:
            _unlink_any(dst)
            removed.append(name)

    print("", file=sys.stderr)
    if removed:
        print(f"jxtest uninstall: removed {len(removed)} links", file=sys.stderr)
        for n in removed:
            print(f"  ✓ {n}", file=sys.stderr)
    elif args.dry_run and would_remove:
        print(f"[dry-run] {would_remove} links would be removed "
              f"(re-run without --dry-run to actually remove)", file=sys.stderr)
    else:
        print("jxtest uninstall: nothing to remove", file=sys.stderr)
    if not_jxtest:
        print(f"\n  Skipped (not jxtest links):", file=sys.stderr)
        for n in not_jxtest:
            print(f"    {n}", file=sys.stderr)

    _uninstall_cli(args)


def main() -> None:
    # When invoked via `bin/jxtest install` (no subcommand), default to install.
    # When invoked directly (`python3 install.py ...`), argparse handles the
    # required subcommand as usual. Strip the auto-injected default back out
    # when the user passed one explicitly.
    raw = sys.argv[1:]
    if raw and raw[0] not in ("install", "uninstall", "-h", "--help"):
        sys.argv = [sys.argv[0], "install", *raw]

    ap = argparse.ArgumentParser(description="Install/uninstall the jxtest CLI and Claude Code skills")
    sub = ap.add_subparsers(dest="cmd")

    p_install = sub.add_parser("install", help="Link skills into ~/.claude/skills/ and the CLI onto PATH")
    p_install.add_argument("--dry-run", action="store_true",
                           help="Show what would happen without modifying anything")
    p_install.add_argument("--force", action="store_true",
                           help="Replace real files/dirs sitting at the target paths")

    p_uninstall = sub.add_parser("uninstall", help="Remove what install created")
    p_uninstall.add_argument("--dry-run", action="store_true",
                             help="Show what would happen without modifying anything")
    p_uninstall.add_argument("--force", action="store_true", help=argparse.SUPPRESS)

    args = ap.parse_args()
    {"install": cmd_install, "uninstall": cmd_uninstall}[args.cmd](args)


if __name__ == "__main__":
    main()
